-- Luacheck configuration for Control4 DriverWorks

-- Allow these Control4 globals
globals = {
  "C4",
  "Properties",
  "JSON",
  "OBJDEF",
  -- Driver state
  "Navigators",
  "Navigator",
  "Timer",
  "Config",
  "PlaybackState",
  "Queue",
  "Browse",
  "Auth",
  "AUTH_TOKEN_TTL_S",
  "MAX_CACHED_NODES",
  "MCWS",
  "DeviceSelected",
  "PlayerSelected",
  "PLAYER",
  "SWITCH",
  "Transport",
  "GlobalTicketHandlers",
  "RFP",
  -- Constants
  "TAB_PATHS",
  "SCREEN_TABS",
  "TRACK_FIELDS",
  "IMAGE_SIZES",
  "NOW_PLAYING_ART_SIZE",
  "LastSwitcherHide",
  "SWITCHER_HIDE_INTERVAL_S",
  "MSP_BINDING",
  "PLAYER_BINDING",
  "SWITCH_BINDING",
  "KEY_MAP",
  "HOLD_REPEAT_MS",
  "LastViewCommand",
  "VIEW_DEBOUNCE_S",
  "UI_MODE_THEATER",
  "MCC_THEATER_VIEW",
  "MCC_SHOW_STANDARD_VIEW",
  "THEATER_MODE_TOGGLE",
  "THEATER_MODE_HOME",
  "THEATER_MODE_PLAYING_NOW",
  "THEATER_MODE_AUDIO",
  "SEEK_STEP_MS",
  "SCAN_REPEAT_MS",
  "IDLE_POLL_MS",
  "UnhandledCommands",
  "VARIABLES",
  "VariableCache",
  "Connected",
  "DRIVER_VERSION",
  -- Lifecycle callbacks
  "OnDriverLateInit",
  "OnDriverDestroyed",
  "OnPropertyChanged",
  -- HTTP callbacks
  "ReceivedAsync",
  -- Proxy callbacks
  "ReceivedFromProxy",
  "OnSystemEvent",
  "ExecuteCommand",
  -- Helper functions (defined in file)
  "dbg",
  "log",
  "Now",
  "URLEncode",
  "MakeQuery",
  "ResetBrowseCache",
  "CacheFresh",
  "PruneCache",
  "PlayNode",
  "ActionRows",
  "SplitBrowsePath",
  "PlayBrowsePath",
  "PlayPlaylistByName",
  "PROGRAMMING",
  "Seek",
  "SendKeys",
  "InTheaterView",
  "ShowTheaterView",
  "LeaveTheaterView",
  "ViewCommandRepeated",
  "StartKeyRepeat",
  "StopKeyRepeat",
  "NoUIValue",
  "HideSwitcherInAllRooms",
  "PushNowPlaying",
  "SetupVariables",
  "SetVar",
  "FireDriverEvent",
  "PublishState",
  "PublishUiState",
  "SetConnected",
  "StartScan",
  "StopScan",
  "ReportUnhandled",
  "EffectivePosition",
  "DataReceived",
  "DataReceivedError",
  "SendEvent",
  "MakeList",
  "XMLEncode",
  "XMLTag",
  "FileImageUrl",
  "NodeImageUrl",
  "BuildImageList",
  "ImageListForFile",
  "ImageListForNode",
  "DefaultImageList",
  "ImageListForAsset",
  "UpdateMediaInfo",
  "UpdateProgress",
  "UpdateDashboard",
  "UpdateQueue",
  "ApplyPlaybackInfo",
  "ApplyUiInfo",
  "UiModeName",
  "RefreshPlayModes",
  "RefreshQueue",
  "FormatTime",
  "ActiveSessionCount",
  "CurrentPollInterval",
  "StartPolling",
  "UpdatePollRate",
  "PollSoon",
  "PollNow",
  "KillAllTimers"
}

-- Ignore certain warnings
ignore = {
  "212", -- Unused argument
  "213"  -- Unused loop variable
}

-- No limits
max_line_length = false
max_cyclomatic_complexity = false
